// Generated by diesel_ext

#![allow(unused)]
#![allow(clippy::all)]

use chrono::NaiveDateTime;
use diesel::Queryable;
use serde::{Deserialize, Serialize};
use uuid::Uuid;

#[derive(Queryable, Debug, Deserialize, Serialize)]
pub struct Customer {
    pub id: Uuid,
    pub username: String,
    pub password_hash: String,
    pub email: String,
    pub created_at: Option<NaiveDateTime>,
}

#[derive(Queryable, Debug, Deserialize, Serialize)]
pub struct Order {
    pub id: Uuid,
    pub customer_id: Uuid,
    pub status: crate::routes::order::order::OrderStatus,
    pub created_at: NaiveDateTime,
    pub product_id: Uuid,
}

#[derive(Queryable, Debug, Deserialize, Serialize)]
pub struct Product {
    pub id: Uuid,
    pub name: String,
    pub is_available: bool,
    pub price: i32,
}

#[derive(Queryable, Debug, Deserialize, Serialize)]
pub struct Admin {
    pub id: Uuid,
    pub username: String,
    pub password_hash: String,
}
